package org.boot.course.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.boot.course.dao.entity.SchoolInfo;
import org.boot.course.dao.entity.SchoolInfoExample;

public interface SchoolInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    long countByExample(SchoolInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    int deleteByExample(SchoolInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    int insert(SchoolInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    int insertSelective(SchoolInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    List<SchoolInfo> selectByExample(SchoolInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    SchoolInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") SchoolInfo record, @Param("example") SchoolInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    int updateByExample(@Param("record") SchoolInfo record, @Param("example") SchoolInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    int updateByPrimaryKeySelective(SchoolInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Sun Mar 21 11:54:14 CST 2021
     */
    int updateByPrimaryKey(SchoolInfo record);
}